### ISSUE TITLE
Volume Knob Sends Channel to Zero and holds it there

### ISSUE THREAD

**Issue by SuspiciousWizard** [oddbear/Loupedeck.WaveLink.Plugin#3]
First of all, just wanted to say that I love this. This is exactly what I want to do with Loupedeck and Wavelink. Recently when I try to adjust the volume for a specific channel with the knob on the Loupedeck it takes the specified channel volume to zero, and holds it there. When you try and use the mouse to set the faders back to their previous level the fader gets pulled back to zero. The only way to release the faders is to quite the Loupedeck software.

Thanks for your hard work on this. It's awesome.

**Comment by oddbear** [comment]
Hi, thanks for the feedback.

What version of the WaveLink software are you using, macOS or Windows, and what Wave device?

I have had this problem a few times only, but have not been able to see why the WaveLink Software does this. I can do some small tweaks to ignore the WaveLink value if it seems corrupted, to see if that helps.

**Comment by oddbear** [comment]
You can try out the latest v0.8.0 release to see if this helps: https://github.com/oddbear/Loupedeck.WaveLink.Plugin/releases/tag/v0.8.0

**Comment by SuspiciousWizard** [comment]
That seems to have fixed the issue. Thanks!

_Erik

Erik Tait
www.ErikTait.com
International Champion of Close Up Magic
As seen on Penn & Teller: Fool Us
614-753-2985
***@***.***

**Comment by oddbear** [comment]
Great 👍 will se if it's possible to get this to the Markedplace soon. Just want to test it on macOS first also.
Thanks for testing.
