### ISSUE TITLE
Will not Uninstall

### ISSUE THREAD

**Issue by SuspiciousWizard** [oddbear/Loupedeck.WaveLink.Plugin#4]
Not sure if this is a plugin problem or a Loupedeck Problem. But I noticed that I can't uninstall the plugin, and I can't find a file in the directory to manually remove it.

**Comment by oddbear** [comment]
Hi.

It's supposed to be in `C:\Users\<username>\AppData\Local\Loupedeck\Plugins\WaveLink`.

Stopping Louepdeck, deleting that folder, and start Loupedeck again should remove everything.

Also check: `C:\Users\<username>\AppData\Local\Loupedeck\Logs\plugin_crashes` to see if there is anything there. That's a special folder that will make the plugins unusable if it contains a file with the plugin name.
