### ISSUE TITLE
Loupedeck update broke this

### ISSUE THREAD

**Issue by Jdav00** [oddbear/Loupedeck.WaveLink.Plugin#7]
THe new version of loupedeck (v6) seems to have broken this. I can not reinstall plugin from file. 

![image](https://github.com/user-attachments/assets/4d46295e-eaf5-4e5e-832b-bfbdf8f28d90)
![image](https://github.com/user-attachments/assets/922ff452-9c3e-4aa1-b795-c949134ca454)

**Comment by oddbear** [comment]
Hi, I see you got the VolumeControl working, are you using this plug also?

I can try updating it for Loupedeck 6, but I am not sure if I am able to test it. Since this is not updated for newest version of the WaveLink software, I might even not find an old enough installer.

**Comment by Jdav00** [comment]
No I'm good with the VolumeControl plugin, Closing this out. Now to find a working Discord plugin...

Thanks for the continued hardwork on Loupedeck stuff! Slim Pickins out here for this thing. Keep it up!

**Comment by oddbear** [comment]
Great, when I have time, I would like to continue with this one, but then updated for the latest version WaveLink. The protocol there is very different.
